name: Build all core packages

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    name: Build Packages with external toolchain
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: False
      matrix:
        include:
          - target: x86/64
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.target }}
      build_kernel: true
      build_all_kmods: true
      build_all_modules: true
      build_full: true

